console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'
    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = '<magenta>  ( {{ .HEAD }} )</magenta>'
    foreground = 'reset'
    background = 'transparent'
    type = 'git'
    style = 'plain'
    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = ''
      cache_duration = 'none'
      fetch_status = true
      show_status = true
      show_branch = true
      show_ahead = true
      show_behind = true
      show_staged = true
      show_changed = true
      show_untracked = true
      show_conflicted = true
      show_stash = true
      show_dirty = true
      show_clean = true
      show_detached = true

  # Programmiersprachen-Segmente nach git
  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    foreground = 'p:pistachio_green'
    background = 'transparent'
    template = ' {{ .Full }}'

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'p:terminal_yellow'
    background = 'transparent'
    template = ' {{ .Full }}'

  [[blocks.segments]]
    type = 'go'
    style = 'plain'
    foreground = 'p:light_sky_blue'
    background = 'transparent'
    template = ' {{ .Full }}'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']
    [blocks.segments.properties]
      cache_duration = 'none'
